#+title: Diseño de Interfaces
#+author: Edgar Quiroz
#+language: es
#+latex_header: \usepackage[spanish]{babel}
#+latex_header: \usepackage{arev}
#+latex_header: \usepackage[margin=1.5cm]{geometry}

* UML

En cualquier intento colaborativo para desarrollar software debe haber una forma
de especificar que se va a hacer. En equipos grandes y multidisciplinario esto
es un problema, pues comunicación directa no es práctica, y las diferentes áreas
de todos no permiten usar lenguaje técnico.

Para resolver esto se creó UML (Universal Modelling Language). Es un estándar de
decenas de diferentes tipos de diagramas, cada uno de ellos especializado en
especificar algún aspecto del sistema de software de manera simple y no técnica.

** Diagramas de clases

Permiten modelar parte del sistema de software usando orientación a objetos.
En breve, diferentes elementos y actores se agrupan en clases. Cada clase tiene
ciertas caracterísicas propias, y puede interactuar con las otras clases a
través de métodos.

** Diagramas de flujo

Permiten modelar un algoritmo. Se pueden tomar decisiones, asignar variables y
definir ciclos. Estos algoritmos normalmente reflejan un proceso que se quiere
automatizar en el sistema.


* Interacciones Humano-Máquina

Estudia el diseño, evaluación e implementación de sistemas computacionales
interactivos. En otras palabras, mecanismos para comunicarse con una máquina.

*Interacción*: acción recíproca entre dos o más agentes

Gran parte del éxito de un sistema está dado por que tan *seguro*, *útil*,
*eficaz* y *usable* es. Esto toma lugar en *interfaces*.

+ *Seguro*: robusto a ataques
+ *Útil*:
+ *Eficaz*: hace el software productivo y ahorra costos de capacitación.
+ *Úsabilidad*: se sencillo e intuitivo.

*Tarea*: diseñar reglas para jugar serpientes y escaleras usando únicamente
texto.

Para llegar a mecanismos con estas características, en general se estudia como
interactúan las personas interractúan con su ambiente y con otras personas, e
intentar replicarla.

** Algo de historia

Un ejemplo sería la *ENIAC*. Ésta se configuraba con más de 6000 interruptores.
Para usarla había que tener un conocimiento muy profundo de la aquitectura de la
máquina, y modificaciones a su funcionamiento tomaba semanas.

Una mejora a esto fue la introducción de *teletipos* (con tarjetas perforadas).
Esto facilitaba la forma de modificar el software de la máquina.

En 1968, Xerox creó la primera *interfaz gráfica*. Poseía un mouse, ventanas,
íconos y menúes.
