#+title:  Aplicación web para el proceso Educativo sobre el Logaritmo
#+subtitle: Opinión del diseño
#+options: toc:nil
#+language: es
#+latex_header: \usepackage[spanish]{babel}
#+latex_header: \usepackage[margin=1.5cm]{geometry}
#+latex_header: \usepackage{biblatex}
#+latex_header_extra: \addbibresource{refs.bib}
#+latex_header: \usepackage{arev}

Revisa el artículo
\cite{Salas-Rueda_Gamboa-Rodríguez_Salas-Rueda_Salas-Rueda_2020}. Contesta la
siguiente pregunta utilizando los conceptos de usabilidad discutidos en la clase

+ ¿Cuál es tu opinión sobre la Aplicación web para el proceso Educativo sobre
  el Logaritmo (AEL)?

  A grandes rasgo, me parece que es una aplicación que tomó muy bien en cuenta
  su objetivo y sus usuarios, al ser extremadamente simple. Esto la hace ideal
  para mostrar algunos aspectos aparentemente obvios del buen diseño. Por
  ejemplo, una fuente de colores oscuros con un fondo blanco permiten buena
  legibilidad. Aún así, hay varios aspecto que se podrían mejorar usando los
  criterios vistos en clase.

  Primero, hay que considerar la conetividad y la navegación. En las veces que
  intenté usarla, actualizar la página tardó varios segundos, lo que hace
  incómodo su uso. Más aún, tener que recargar la página entera para tener
  interactividad en una aplicación tan simple se me hace extraño. Me parece que
  ambos problemas serían solucionados, al menos en parte, remplazando los
  componentes interactivos con alternativas que no requieran recargar la página.

  Luego, respecto a la consistencia visual, la aplicación tiene tres fuentes
  distintas y tres colores diferentes. Si bien las fuentes tienen diferentes
  roles, estas podrían ser unificadas en una sola familia de fuentes. En cuanto
  al color, no encuentro ningún patrón relavante, así que cambiar todo a un solo
  color ayudaría con la consistencia. En otro aspecto de la consistencia, los
  elementos se mueven levemente en cada recarga de la página. Esto se podría
  solucionar con el punto anterior.

  Finalmente, no me parece que la cara tenga algún propósito más que estético,
  por lo que consideraría prudente retirarla.

  A pesar de sus oportunidades para mejorar, el hecho de que sea tan simple hace
  que estos detalles de diseño no afecten tanto la usabilidad, como se mostró en
  las pruebas de usuario exhibidas en el artículo.

\printbibliography
